### ISSUE TITLE
为什么splash页面状态栏是黑色的

### ISSUE THREAD

**Issue by protectedMan** [dueeeke/EasySplash#1]
如何做到状态栏沉浸呢。

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/67612043-c2cdbf00-f7d1-11e9-831a-e802c5b95679.png)

**Comment by Doikki** [comment]
什么手机，如果是oppo和vivo的手机可能需要去设置里面开启一下全屏显示

**Comment by protectedMan** [comment]
需要用户手动介入是吧

**Comment by Doikki** [comment]
是的
